const SET_QUESTIONS_FILTER = 'questions/filter';

const QUESTIONS_REQUEST = '@@QUESTION/QUESTIONS_REQUEST'
const QUESTIONS_SUCCESS = '@@QUESTION/QUESTIONS_SUCCESS'
const QUESTIONS_FAILURE = '@@QUESTION/QUESTIONS_FAILURE'

const POST_REQUEST = '@@QUESTION/POST_REQUEST'
const POST_SUCCESS = '@@QUESTION/POST_SUCCESS'
const POST_FAILURE = '@@QUESTION/POST_FAILURE'

const DELETE_REQUEST = '@@QUESTION/DELETE_REQUEST'
const DELETE_SUCCESS = '@@QUESTION/DELETE_SUCCESS'
const DELETE_FAILURE = '@@QUESTION/DELETE_FAILURE'

const PUT_REQUEST = '@@QUESTION/PUT_REQUEST'
const PUT_SUCCESS = '@@QUESTION/PUT_SUCCESS'
const PUT_FAILURE = '@@QUESTION/PUT_FAILURE'

const types = {
  SET_QUESTIONS_FILTER,
  QUESTIONS_REQUEST,
  QUESTIONS_SUCCESS,
  QUESTIONS_FAILURE,
  POST_REQUEST,
  POST_SUCCESS,
  POST_FAILURE,
  DELETE_REQUEST,
  DELETE_SUCCESS,
  DELETE_FAILURE,
  PUT_REQUEST,
  PUT_SUCCESS,
  PUT_FAILURE
};

export default types;