const SET_AUTHORS_FILTER = 'authors/filter';

const AUTHORS_REQUEST = '@@AUTHOR/AUTHORS_REQUEST'
const AUTHORS_SUCCESS = '@@AUTHOR/AUTHORS_SUCCESS'
const AUTHORS_FAILURE = '@@AUTHOR/AUTHORS_FAILURE'

const POST_REQUEST = '@@AUTHOR/POST_REQUEST'
const POST_SUCCESS = '@@AUTHOR/POST_SUCCESS'
const POST_FAILURE = '@@AUTHOR/POST_FAILURE'

const DELETE_REQUEST = '@@AUTHOR/DELETE_REQUEST'
const DELETE_SUCCESS = '@@AUTHOR/DELETE_SUCCESS'
const DELETE_FAILURE = '@@AUTHOR/DELETE_FAILURE'

const PUT_REQUEST = '@@AUTHOR/PUT_REQUEST'
const PUT_SUCCESS = '@@AUTHOR/PUT_SUCCESS'
const PUT_FAILURE = '@@AUTHOR/PUT_FAILURE'

const types = {
  SET_AUTHORS_FILTER,
  AUTHORS_REQUEST,
  AUTHORS_SUCCESS,
  AUTHORS_FAILURE,
  POST_REQUEST,
  POST_SUCCESS,
  POST_FAILURE,
  DELETE_REQUEST,
  DELETE_SUCCESS,
  DELETE_FAILURE,
  PUT_REQUEST,
  PUT_SUCCESS,
  PUT_FAILURE
};

export default types;